### PR TITLE
Added test for `routeType='pt'`

### PR DESCRIPTION
**Pull request by imoea**

### CODE REVIEW

**Comment by imoea** [comment]
After these changes, the nested dictionary attributes will still remain camel cased.
Wouldn't it be better to stick to the result returned by the API to avoid confusion in this case? It seems that every attribute is camel cased only for this route result.

**Comment by thomasjiangcy** [comment]
Makes sense, let's stick to camel casing for this then. Thanks again!

**Comment by imoea** [comment]
```
class BaseResource:

    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            if hasattr(self, k.lower()):
                setattr(self, k.lower(), v)

    def to_dict(self):
        from .utils import to_dict
return to_dict(self)
```

I'll have to remove the lowering of `k` in the above `__init__()` though. Will this break anything?

**Comment by thomasjiangcy** [comment]
Yes. The alternative would be to map the nested JSON objects into their own classes as well. With each of them having their corresponding snake case counterparts. This might be worthwhile if we want to fully map the responses into Python objects.

**Comment by imoea** [comment]
That seems like too much trouble, especially if the API is not stable and they decide to rename the attributes in the future. Can we apply these changes and close the request for now?

**Comment by thomasjiangcy** [comment]
Fair enough, thanks for this! :)

**Comment by thomasjiangcy** [comment]
Closes #6

**Comment by imoea** [comment]
Thanks for the wrapper. It's been useful!

**Pull request merged**
