### PR TITLE
Added `plan` attribute to `RouteResult()`

### PR DESCRIPTION
**Pull request by imoea**
To accept results for `routeType='pt'`.

### CODE REVIEW

**Comment by thomasjiangcy** [comment]
Seems you'll need to do a quick update on the relevant test as well :)

**Comment by imoea** [comment]
I'm not familiar with testing. How do I go about doing this? Do I construct a new test function in `tests/test_response.py` with the relevant assertions?

**Comment by thomasjiangcy** [comment]
The test that's failing is occurring on [this line](https://github.com/windspeed-io/python-onemapsg/blob/master/tests/test_response.py#L240). I think it should just be a matter of modifying `data` to fit the new attribute in `RouteResult`. So no new tests required, just a slight modification to the existing one ;)

**Comment by imoea** [comment]
Oops I think i created a separate pull request for the test. How do I combine them?

**Comment by thomasjiangcy** [comment]
Hmm I think you might've removed your previous commits in your other pull request, I can only see test code in your other PR. I think the easiest way would be to just include the changes in your other PR and we can close this.

**Pull request closed without merging**
